question_bank = [
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The animated film 'Spirited Away' won the Academy Award for Best Animated Feature at the 75th Academy Awards in 2003.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Studio Ghibli is a Japanese animation studio responsible for the films 'Wolf Children' and 'The Boy and the Beast'.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In Kill La Kill, the weapon of the main protagonist is a katana. ",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "easy",
            "question": "No Game No Life first aired in 2014.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In the 'Melancholy of Haruhi Suzumiya' series, the narrator goes by the nickname Kyon.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The anime Attack on Titan was directed by Tetsurō Araki, the same person who directed the anime Highschool of the Dead.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "hard",
            "question": "Throughout the entirety of 'Dragon Ball Z', Goku only kills two characters: a miniboss named Yakon and Kid Buu.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "hard",
            "question": "Druid is a mage class in 'Log Horizon'.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In the 'To Love-Ru' series, Golden Darkness is sent to kill Lala Deviluke.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In Chobits, Hideki found Chii in his apartment.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "hard",
            "question": "The character Plum from 'No Game No Life' is a girl.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "medium",
            "question": "In Full Metal Panic!, Whispered are those who are capable of creating Black Technology.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
    ]